


-- MySQL Script generated by MySQL Workbench
-- 06/08/17 09:50:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema danza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema danza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `danza` DEFAULT CHARACTER SET utf8 ;
USE `danza` ;

-- -----------------------------------------------------
-- Table `danza`.`tipoDanza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `danza`.`tipoDanza` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `danza`.`maestro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `danza`.`maestro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(90) NOT NULL,
  `correo` VARCHAR(254) NULL,
  `telefono` VARCHAR(22) NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `danza`.`grupoClase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `danza`.`grupoClase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idTipoDanza` INT NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  `costo_mensual` DECIMAL(8,2) NOT NULL,
  `terminado` TINYINT(1) NOT NULL DEFAULT 0,
  `fecha_termino` VARCHAR(45) NULL,
  `idMaestro` INT NOT NULL,
  `porcentaje_ganancia_maestro` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `grupo_tipodanza_idx` (`idTipoDanza` ASC),
  INDEX `grupo_maestro_idx` (`idMaestro` ASC),
  CONSTRAINT `grupo_tipodanza`
    FOREIGN KEY (`idTipoDanza`)
    REFERENCES `danza`.`tipoDanza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `grupo_maestro`
    FOREIGN KEY (`idMaestro`)
    REFERENCES `danza`.`maestro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `danza`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `danza`.`horario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dia` ENUM('lun','mar','mie','jue','vie','sab') NOT NULL,
  `horainicio` TIME NOT NULL,
  `horafinal` TIME NOT NULL,
  `idGrupoClase` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `horario_grupo_idx` (`idGrupoClase` ASC),
  CONSTRAINT `horario_grupo`
    FOREIGN KEY (`idGrupoClase`)
    REFERENCES `danza`.`grupoClase` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `danza`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `danza`.`alumno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(254) NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(22) NULL,
  `telefono_emergencia` VARCHAR(22) NOT NULL,
  `tipo_sangre` VARCHAR(45) NULL,
  `activo` TINYINT(1) NOT NULL,
  `diapago` DATE NULL,
  `foto` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_inscripcion` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `danza`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `danza`.`asistencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dia` DATE NOT NULL,
  `idGrupoClase` INT(11) NOT NULL,
  `idAlumno` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `asistencia_clase_idx` (`idGrupoClase` ASC),
  INDEX `asistencia_alumno_idx` (`idAlumno` ASC),
  CONSTRAINT `asistencia_clase`
    FOREIGN KEY (`idGrupoClase`)
    REFERENCES `danza`.`grupoClase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `asistencia_alumno`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `danza`.`alumno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `danza`.`promociones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `danza`.`promociones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(90) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `porcentaje_descuento` INT NOT NULL,
  `aplica_para` ENUM('INSCRIPCION','MENSUALIDAD') NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `danza`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `danza`.`ingreso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `monto` DECIMAL(12,2) NOT NULL,
  `descripcion` VARCHAR(400) NULL,
  `fecha` DATE NOT NULL,
  `idPromocion` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idPromocion_idx` (`idPromocion` ASC),
  CONSTRAINT `promocion_ingreso`
    FOREIGN KEY (`idPromocion`)
    REFERENCES `danza`.`promociones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `danza`.`mensualidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `danza`.`mensualidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idalumno` INT NOT NULL,
  `idingreso` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `mensualidad_alumno_idx` (`idalumno` ASC),
  INDEX `mensualidad_ingreso_idx` (`idingreso` ASC),
  CONSTRAINT `mensualidad_alumno`
    FOREIGN KEY (`idalumno`)
    REFERENCES `danza`.`alumno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mensualidad_ingreso`
    FOREIGN KEY (`idingreso`)
    REFERENCES `danza`.`ingreso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `danza`.`alumno_grupo_aux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `danza`.`alumno_grupo_aux` (
  `idalumno` INT NOT NULL,
  `idclase` INT NOT NULL,
  PRIMARY KEY (`idalumno`, `idclase`),
  INDEX `alumno_grupo_aux_idx` (`idalumno` ASC),
  INDEX `grupo_alumno_idx` (`idclase` ASC),
  CONSTRAINT `alumno_grupo_aux`
    FOREIGN KEY (`idalumno`)
    REFERENCES `danza`.`alumno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `grupo_alumno`
    FOREIGN KEY (`idclase`)
    REFERENCES `danza`.`grupoClase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `danza`.`inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `danza`.`inscripcion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idalumno` INT NOT NULL,
  `idingreso` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `incripcion_alumno_idx` (`idalumno` ASC),
  INDEX `inscripcion_ingreso_idx` (`idingreso` ASC),
  CONSTRAINT `incripcion_alumno`
    FOREIGN KEY (`idalumno`)
    REFERENCES `danza`.`alumno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `inscripcion_ingreso`
    FOREIGN KEY (`idingreso`)
    REFERENCES `danza`.`ingreso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `danza`.`egreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `danza`.`egreso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `monto` DECIMAL(12,2) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `danza`.`pagodesalario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `danza`.`pagodesalario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idmaestro` INT NOT NULL,
  `idegreso` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `pago_maestro_idx` (`idmaestro` ASC),
  INDEX `egreso_pago_idx` (`idegreso` ASC),
  UNIQUE INDEX `idegreso_UNIQUE` (`idegreso` ASC),
  CONSTRAINT `pago_maestro`
    FOREIGN KEY (`idmaestro`)
    REFERENCES `danza`.`maestro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `egreso_pago`
    FOREIGN KEY (`idegreso`)
    REFERENCES `danza`.`egreso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `danza`.`gastovariable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `danza`.`gastovariable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idEgreso` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `gastovariable_egreso_idx` (`idEgreso` ASC),
  CONSTRAINT `gastovariable_egreso`
    FOREIGN KEY (`idEgreso`)
    REFERENCES `danza`.`egreso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `danza`.`mensualidad_grupoclase_aux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `danza`.`mensualidad_grupoclase_aux` (
  `id_mensualidad` INT NOT NULL,
  `id_grupo_clase` INT NOT NULL,
  PRIMARY KEY (`id_grupo_clase`, `id_mensualidad`),
  INDEX `mensualidad_grupoFK_idx` (`id_mensualidad` ASC),
  INDEX `grupo_mensualidadFK_idx` (`id_grupo_clase` ASC),
  CONSTRAINT `mensualidad_grupoFK`
    FOREIGN KEY (`id_mensualidad`)
    REFERENCES `danza`.`mensualidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `grupo_mensualidadFK`
    FOREIGN KEY (`id_grupo_clase`)
    REFERENCES `danza`.`grupoClase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

